language: ruby
rvm:
- 2.1

install: gem install jekyll html-proofer
script: jekyll build && htmlproofer ./_site

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

notifications:
  webhooks:
    urls:
      - https://bugs.spamty.eu/index.php?page=api&project=blog&XMODE=travisci # docs: https://github.com/Spamty/Bumpy-Booby/blob/master/API.md#travis-ci-api
    on_success: always
    on_failure: always
    on_start: always
