# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spamty Blog
description: "We will inform you here about everything new about Spamty.eu."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.spamty.eu" # the base hostname & protocol for your site
permalink: pretty # structure /:categories/:year/:month/:day/:title/
twitter_username: spamty
github_username: Spamty
timezone: UTC

# Build settings
markdown: kramdown

# exclude some files
exclude: ["README.md", "docs/"]